# Generated by Django 5.0.6 on 2024-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='car',
            field=models.ManyToManyField(to='car.carmodel'),
        ),
    ]
