# Generated by Django 5.0.6 on 2024-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_commentmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
